apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ojo8kzw20-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ojo8kzw20-java-springboot-gitops